apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: healthsync  # Optional if you're deploying in a specific namespace
spec:
  type: LoadBalancer
  ports:
    - port: 80             # External port to expose the service
      targetPort: 8084     # Port inside the container
  selector:
    app: patient-service   # Matches the label in the Deployment
